mainproject/api/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('dashboard.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
]

mainproject/dashboard/urls.py
from django.urls import include, path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "dashboard"
urlpatterns = [
    path('users/', views.UserListView.as_view(), name='users'),
    path('users/create/', csrf_exempt(views.UserCreateView.as_view()), name='users_create'),
    path('users/<int:pk>/', views.UserDetailView.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

mainproject/mainproject/urls.py
from django.contrib import admin
from django.urls import include, path
from dashboard import views as dashboard_views
from api import views as api_views

urlpatterns = [
    path('dashboard/', dashboard_views.home, name='dashboard'),
    path('login/', dashboard_views.login, name='login'),
    path('admin/', admin.site.urls),
    
    path('api/v1/', include('api.urls')),
]

mainproject/api/models.py
from django.db import models

# Create your models here.

mainproject/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser, User
from datetime import datetime

# Create your models here.

class CustomUser(AbstractUser):
    name = models.CharField(blank=True, max_length=255)
    firebase_auth = models.TextField(null=True, blank=True, max_length=255)
    firebase_uid = models.TextField(null=True, blank=True, max_length=255)

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        return super(CustomUser, self).save(*args, **kwargs)

class Setting(models.Model):
    api_key = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.api_key


class Log_Category(models.Model):
    name = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name

    def soft_delete(self):
        self.deleted_at = datetime.now()
        self.save()

class Log(models.Model):
    log = models.TextField(max_length=255)
    category = models.ForeignKey(
        Log_Category, related_name='logs', on_delete=models.CASCADE,
        blank=True, null=True)
    user = models.ForeignKey(CustomUser, related_name='logs',
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.log

mainproject/dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email', 'firebase_uid')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

mainproject/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from rest_framework import generics
from . import models, serializers
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from rest_framework.response import Response

class UserListView(generics.ListCreateAPIView):
    queryset = models.CustomUser.objects.all()
    serializer_class = serializers.UserSerializer

class UserCreateView(generics.CreateAPIView):
    queryset = models.CustomUser.objects.all()
    serializer_class = serializers.UserSerializer

class UserDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.CustomUser.objects.all()
    serializer_class = serializers.UserSerializer

# Create your views here.
def home(request):
    setting = models.Setting.objects.all()
    return render(request, 'home.html', {'boards': setting})

def login(request):
    return render(request, 'login.html')
    

mainproject/templates/login.html
{% load static %}
{% load fullurl %}
<!doctype html>
<!--[if lte IE 9]> <html class="lte-ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!-->
<html lang="en">
<!--<![endif]-->

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="msapplication-tap-highlight" content="no" />

    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon-16x16.png' %}" sizes="16x16">
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon-32x32.png' %}" sizes="32x32">

    <title>Altair Admin v2.9.1 - Login Page</title>

    <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500' rel='stylesheet' type='text/css'>

    <!-- uikit -->
    <link rel="stylesheet" href="{% static 'bower_components/uikit/css/uikit.almost-flat.min.css' %}" />

    <!-- altair admin login page -->
    <link rel="stylesheet" href="{% static 'assets/css/login_page.min.css' %}" />
</head>

<body class="login_page">
    <div class="login_page_wrapper">
        <div class="uk-alert uk-alert-success" data-uk-alert="" id="uk-alert-success" style="display: none">
            <a href="#" class="uk-alert-close uk-close"></a>
            Account has been created
        </div>
        <div class="md-card" id="login_card">
            <div class="md-card-content large-padding" id="login_form">
                <div class="login_heading">
                    <div class="user_avatar"></div>
                </div>
                <form>
                    <div class="uk-form-row">
                        <label for="login_email">Email</label>
                        <input class="md-input" type="text" id="login_email" name="login_email" />
                    </div>
                    <div class="uk-form-row">
                        <label for="login_password">Password</label>
                        <input class="md-input" type="password" id="login_password" name="login_password" />
                    </div>
                    <div class="uk-margin-medium-top">
                        <a class="md-btn md-btn-primary md-btn-block md-btn-large" id="button_sign_in" name="button_sign_in">Sign In</a>
                    </div>
                    <div class="uk-grid uk-grid-width-1-2 uk-grid-small uk-margin-top">
                        <div>
                            <a href="#" class="md-btn md-btn-block md-btn-facebook" data-uk-tooltip="{pos:'bottom'}" title="Sign in with Facebook">
                                <i class="uk-icon-facebook uk-margin-remove"></i>
                            </a>
                        </div>
                        <div>
                            <a href="#" class="md-btn md-btn-block md-btn-gplus" data-uk-tooltip="{pos:'bottom'}" title="Sign in with Google+">
                                <i class="uk-icon-google-plus uk-margin-remove"></i>
                            </a>
                        </div>
                    </div>
                    <div class="uk-margin-top">
                        <a href="#" id="login_help_show" class="uk-float-right">Need help?</a>
                        <span class="icheck-inline">
                            <input type="checkbox" name="login_page_stay_signed" id="login_page_stay_signed" data-md-icheck />
                            <label for="login_page_stay_signed" class="inline-label">Stay signed in</label>
                        </span>
                    </div>
                </form>
            </div>
            <div class="md-card-content large-padding uk-position-relative" id="login_help" style="display: none">
                <button type="button" class="uk-position-top-right uk-close uk-margin-right uk-margin-top back_to_login"></button>
                <h2 class="heading_b uk-text-success">Can't log in?</h2>
                <p>Here’s the info to get you back in to your account as quickly as possible.</p>
                <p>First, try the easiest thing: if you remember your password but it isn’t working, make sure that Caps Lock
                    is turned off, and that your username is spelled correctly, and then try again.</p>
                <p>If your password still isn’t working, it’s time to
                    <a href="#" id="password_reset_show">reset your password</a>.</p>
            </div>
            <div class="md-card-content large-padding" id="login_password_reset" style="display: none">
                <button type="button" class="uk-position-top-right uk-close uk-margin-right uk-margin-top back_to_login"></button>
                <h2 class="heading_a uk-margin-large-bottom">Reset password</h2>
                <form>
                    <div class="uk-form-row">
                        <label for="login_email_reset">Your email address</label>
                        <input class="md-input" type="text" id="login_email_reset" name="login_email_reset" />
                    </div>
                    <div class="uk-margin-medium-top">
                        <a href="index.html" class="md-btn md-btn-primary md-btn-block">Reset password</a>
                    </div>
                </form>
            </div>
            <div class="md-card-content large-padding" id="register_form" style="display: none">
                <button type="button" class="uk-position-top-right uk-close uk-margin-right uk-margin-top back_to_login"></button>
                <h2 class="heading_a uk-margin-medium-bottom">Create an account</h2>
                <form id="form_validation">
                    <div class="uk-form-row">
                        <label for="register_username">Username</label>
                        <input class="md-input" type="text" id="register_username" name="register_username" required/>
                    </div>
                    <div class="uk-form-row">
                        <label for="register_email">E-mail</label>
                        <input class="md-input" type="email" id="register_email" name="register_email" required/>
                    </div>
                    <div class="uk-form-row">
                        <label for="register_password">Password</label>
                        <input class="md-input" type="password" id="register_password" name="register_password" required/>
                    </div>
                    <div class="uk-form-row">
                        <label for="register_password_repeat">Repeat Password</label>
                        <input class="md-input" type="password" id="register_password_repeat" name="register_password_repeat" required/>
                    </div>
                    <div class="uk-margin-medium-top">
                        <a class="md-btn md-btn-primary md-btn-block md-btn-large" name="button_sign_up">Sign Up</a>
                    </div>
                </form>
            </div>
        </div>
        <div class="uk-margin-top uk-text-center">
            <a id="signup_form_show">Create an account</a>
        </div>
    </div>

    <!-- common functions -->
    <script src="{% static 'assets/js/common.min.js' %}"></script>
    <!-- uikit functions -->
    <script src="{% static 'assets/js/uikit_custom.min.js' %}"></script>
    <!-- altair core functions -->  
    <script src="{% static 'assets/js/altair_admin_common.min.js' %}"></script>
    <!-- altair login page functions -->
    <script src="{% static 'assets/js/pages/login.min.js' %}"></script>
    <script src="{% static 'assets/js/pages/components_notifications.min.js' %}"></script>

    <!-- firebase -->
    <script src="https://www.gstatic.com/firebasejs/5.0.4/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.0.4/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.0.4/firebase-database.js"></script>

    <!--  firebase.js-->
    <script src="{% static 'assets/js/firebase.js' %}"></script>

    <script>
        if (sessionStorage.getItem("register")) {
            $('#uk-alert-success').show();
            sessionStorage.removeItem("register");
        }

        $('a[name=button_sign_up]').on('click', function () { 
            var username = $('input[name=register_username]').val()
            var email = $('input[name=register_email]').val() 
            var password = $('input[name=register_password]').val() 
            var password_repeat = $('input[name=register_password_repeat]').val()

            if (password === password_repeat) {
                firebase.auth().createUserWithEmailAndPassword(email, password).then(function(user) {
                var user = firebase.auth().currentUser;
                var userID = user.uid;

                firebase.database().ref('users/' + userID).set({
                    email: email,
                    username: username,
                    password: password,
                    is_deleted: false
                })

                var form_data = {
                    'username': username,
                    'name': username,
                    'email': email,
                    'password': password,
                    'firebase_uid': userID
                }

                var csrftoken = getCookie('csrftoken');

                $.ajax({
                    url: "{% url 'dashboard:users_create' %}",
                    type: "POST",
                    data: JSON.stringify(form_data),
                    dataType: "json",
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken
                    },
                    success: function (response) {
                        sessionStorage.setItem("register", true);
                        location.reload();
                    },
                    error: function(jqXHR, textStatus, errorThrown) {
                        console.log(textStatus, errorThrown);
                    }
                });

            }).catch(function(error) {
                    var errorCode = error.code;
                    var errorMessage = error.message;
                    if (errorCode == 'auth/weak-password') {
                        alert('The password is too weak.');
                    } else {
                        alert(errorMessage);
                    }
                    console.log(error);
                });
            } else {
                alert('password incorrect');
            }
        })

        $('a[name=button_sign_in]').on('click', function () {
            var email = $('input[name=login_email]').val()
            var password = $('input[name=login_password]').val()

            firebase.auth().signInWithEmailAndPassword(email, password).then(function (user) {
                var auth = firebase.auth();
                var currentUser = auth.currentUser;
                
                sessionStorage.setItem('refresh_token', currentUser.refreshToken)
                window.location = "{% url 'dashboard' %}"
            }).catch(function(error) {
                var errorCode = error.code;
                var errorMessage = error.message;
                if (errorCode == 'auth/weak-password') {
                    alert('The password is too weak.');
                } else {
                    alert(errorMessage);
                }
                console.log(error);
            });
        })

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    </script>

</body>
</html>